services:
  digital-record-dev:
    profiles:
      - dev
    image: digital-records
    container_name: digital-records
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80

  digital-records:
    profiles:
      - prod
    image: leelhn2345/digital-records
    container_name: digital-records
    labels:
      - traefik.enable=true
      - traefik.http.routers.digital-records.rule=Host(`digitalrecords.cloud`)
      - traefik.http.routers.digital-records.entrypoints=websecure
      - traefik.http.routers.digital-records.tls.certresolver=myresolver
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - 80

    networks:
      - digital-network

networks:
  digital-network:
    external: true
