services:
  digital-record-dev:
    profiles:
      - dev
    image: digital-records
    container_name: digital-records
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80

  digital-records:
    profiles:
      - prod
    image: leelhn2345/digital-records
    container_name: digital-records
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN_URL}`) || Host (`www.${DOMAIN_URL}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver
      - com.centurylinklabs.watchtower.enable=true
      # - traefik.http.routers.digital-records.middlewares=redirect-www-to-root@file
    expose:
      - 80

    networks:
      - shared-network

networks:
  shared-network:
    external: true
